# Generated by Django 6.1.1 (makemigrations notes -n note_embedding).

import pgvector.django.indexes
import pgvector.django.vector
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        # VectorField needs the extension the core app enables.
        ("core", "0001_vector_extension"),
        ("notes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="embedding",
            field=pgvector.django.vector.VectorField(
                blank=True, dimensions=384, null=True
            ),
        ),
        migrations.AddIndex(
            model_name="note",
            index=pgvector.django.indexes.HnswIndex(
                ef_construction=64,
                fields=["embedding"],
                m=16,
                name="note_embedding_hnsw",
                opclasses=["vector_cosine_ops"],
            ),
        ),
    ]
